<?php

return [
    'sections' => [
        'personales' => [
            0 => 'nombres',
            1 => 'apellidos',
            2 => 'fecha_nacimiento',
            3 => 'genero',
            4 => 'estado_civil',
            5 => 'licenciatura_id',
            6 => 'domicilio',
            7 => 'telefono',
            8 => 'ocupacion',
            9 => 'contacto_emergencia_nombre',
            10 => 'contacto_emergencia_parentesco',
            11 => 'contacto_emergencia_telefono',
            12 => 'religion',
            13 => 'apnp_tipo_sangre',
            14 => 'apnp_factor_rh',
        ],
        'cuestionario' => [
            0 => 'q1_cond_fisica',
            1 => 'q1_cond_fisica_detalle',
            2 => 'q2_cond_mental',
            3 => 'q2_cond_mental_detalle',
            4 => 'q3_tratamiento',
            5 => 'q3_tratamiento_detalle',
            6 => 'q4_crisis_medica',
            7 => 'q4_crisis_medica_detalle',
            8 => 'q5_alergia',
            9 => 'q5_alergia_detalle',
            10 => 'q6_diag_aprendizaje',
            11 => 'q6_diag_aprendizaje_detalle',
            12 => 'q7_dictamen_psico',
            13 => 'q7_dictamen_psico_detalle',
            14 => 'q8_red_apoyo',
            15 => 'q9_acomp_psicologico',
            16 => 'q10_estado_emocional',
            17 => 'q11_necesita_apoyo',
            18 => 'q11_necesita_apoyo_otro',
            19 => 'q12_info_adicional',
        ],
        'clasificacion' => [
            0 => 'categoria_atencion',
            1 => 'atencion_prioritaria',
        ],
        'notas' => [
            0 => 'notas_coordinador',
        ],
        'bitacora' => [
        ],
    ],
    'section_labels' => [
        'personales' => 'Datos personales y contacto',
        'cuestionario' => 'Cuestionario de salud y bienestar estudiantil',
        'clasificacion' => 'Clasificación de atención',
        'notas' => 'Notas de seguimiento',
        'bitacora' => 'Bitácora de revisiones',
    ],
    'labels' => [
        'id' => 'ID',
        'user_id' => 'Usuario',
        'nombres' => 'Nombre(s)',
        'apellidos' => 'Apellido(s)',
        'fecha_nacimiento' => 'Fecha de Nacimiento',
        'edad' => 'Edad',
        'genero' => 'Sexo / Género',
        'estado_civil' => 'Estado Civil',
        'licenciatura_id' => 'Licenciatura',
        'domicilio' => 'Domicilio Completo',
        'telefono' => 'Teléfono Móvil',
        'contacto_emergencia_nombre' => 'Nombre del Contacto de Emergencia',
        'contacto_emergencia_parentesco' => 'Parentesco',
        'contacto_emergencia_telefono' => 'Teléfono de Emergencia',
        'religion' => 'Religión / Creencias',
        'apnp_tipo_sangre' => 'Tipo de Sangre',
        'apnp_factor_rh' => 'Factor RH',
        'q1_cond_fisica' => 'Condición de salud física diagnosticada',
        'q1_cond_fisica_detalle' => 'Especifique la condición física',
        'q2_cond_mental' => 'Condición de salud mental diagnosticada',
        'q2_cond_mental_detalle' => 'Especifique la condición mental',
        'q3_tratamiento' => 'Bajo tratamiento con medicamentos',
        'q3_tratamiento_detalle' => 'Especifique el o los medicamentos',
        'q4_crisis_medica' => 'Crisis médica en los últimos 12 meses',
        'q4_crisis_medica_detalle' => 'Especifique la crisis',
        'q5_alergia' => 'Alergia diagnosticada',
        'q5_alergia_detalle' => 'Especifique la alergia',
        'q6_diag_aprendizaje' => 'Diagnóstico de aprendizaje o desarrollo',
        'q6_diag_aprendizaje_detalle' => 'Especifique el diagnóstico',
        'q7_dictamen_psico' => 'Dictamen / valoración psicopedagógica',
        'q7_dictamen_psico_detalle' => 'Especifique el dictamen',
        'q8_red_apoyo' => 'Red de apoyo',
        'q9_acomp_psicologico' => 'Ha recibido acompañamiento psicológico',
        'q10_estado_emocional' => 'Estado emocional actual',
        'q11_necesita_apoyo' => 'Tipo de apoyo que necesita',
        'q11_necesita_apoyo_otro' => 'Especifique el tipo de apoyo',
        'q12_info_adicional' => 'Información adicional',
        'categoria_atencion' => 'Categoría de Atención',
        'atencion_prioritaria' => 'Atención Prioritaria',
        'bloqueado' => 'Bloqueado para Alumno',
        'ultimo_editor_id' => 'Último Editor Responsable',
        'notas_coordinador' => 'Notas Clínicas y de Seguimiento del Coordinador',
    ],
];
